### ISSUE TITLE
Windows 下无法运行

### ISSUE THREAD

**Issue by ainuoyan** [XGHeaven/homebox#1]
试了一下，Windows 下无法运行

![image](https://user-images.githubusercontent.com/14355237/84727435-9ca79a00-afc1-11ea-94d6-c76e8f434f79.png)

**Comment by XGHeaven** [comment]
我看下，我一般都是用 docker 跑的，二进制只是个备用方案

**Comment by XGHeaven** [comment]
重新下载最新
