### ISSUE TITLE
怎么分析网络问题，本工具可以提供检测结果并直接给出网络异常原因吗

### ISSUE THREAD

**Issue by jiejingta** [XGHeaven/homebox#20]
比如延迟高/丢包的原因，是否能直接在检测后，显示是 路由器什么地方有问题，或者路由器没问题但是知道是公网的问题

**Comment by XGHeaven** [comment]
额，不好支持。

最开始的设计初衷是仅仅用作内网使用的，所以不考虑检测网络问题，而且 Web 环境也无法做这些检测。
